### GET request - get the entire blockchain
GET http://localhost:3000/blockchain HTTP/1.1

### POST request - create a new transaction
POST http://localhost:3000/transaction HTTP/1.1
Content-Type: application/json

{
    "amount": "1000",
    "sender": "sdasjhdahsddtaka",
    "recepient": "uasyd97ashd9uha98sahahd"
}

### GET request - mine the new block
GET http://localhost:3000/mine HTTP/1.1